"""R1–R3 work contracts. A task is a real work item, not a canned agent answer."""

from .work_steps import RECIPES


def task(identifier, persona, title, inputs, steps, output, agent_work, human_gate):
    return dict(id=identifier, persona=persona, title=title, inputs=inputs,
                steps=steps, output=output, agent_work=agent_work, human_gate=human_gate)


TASKS = [
    task('r1-literature', 'R1', 'Lire et classer la littérature',
         'Question de recherche, corpus autorisé, critères de pertinence',
         ['Définir la question et les critères', 'Lire et annoter chaque source', 'Classer résultats et limites', 'Marquer les sources à approfondir'],
         'Bibliographie commentée et tableau des preuves',
         'Préparer une fiche par source et proposer un classement justifié, avec les lacunes du corpus.',
         'Le doctorant vérifie chaque source et le classement.'),
    task('r1-state-art', 'R1', 'Construire l’état de l’art',
         'Bibliographie validée, plan envisagé, contribution de la thèse',
         ['Choisir les thèmes', 'Comparer les résultats et contradictions', 'Rédiger la synthèse', 'Vérifier les références et la place de la contribution'],
         'Section d’état de l’art sourcée',
         'Proposer un plan et un brouillon en distinguant faits sourcés, synthèse et interprétation.',
         'Le doctorant relit les références et valide l’argument scientifique.'),
    task('r1-hypotheses', 'R1', 'Formuler questions et hypothèses',
         'Problème, observations, état de l’art, contraintes',
         ['Formuler une question mesurable', 'Lister les hypothèses concurrentes', 'Définir leurs prédictions', 'Choisir les preuves qui les départagent'],
         'Registre des hypothèses et critères de réfutation',
         'Proposer des hypothèses concurrentes, prédictions et tests discriminants.',
         'Le doctorant et son encadrant arrêtent les hypothèses retenues.'),
    task('r1-experiment-design', 'R1', 'Concevoir une expérience',
         'Hypothèse, matériel, variables, contraintes et risques',
         ['Choisir variables et témoins', 'Définir protocole et mesures', 'Prévoir analyse et critères d’arrêt', 'Faire approuver le protocole'],
         'Protocole expérimental versionné',
         'Rédiger et critiquer un protocole avec contrôles, unités, risques et données attendues.',
         'Le chercheur responsable approuve avant toute manipulation.'),
    task('r1-experiment-run', 'R1', 'Réaliser une expérience',
         'Protocole approuvé, instruments, échantillons, autorisations',
         ['Vérifier les prérequis', 'Conduire l’essai hors de Passage', 'Consigner paramètres et écarts', 'Déposer observations et preuves'],
         'Compte rendu d’essai avec données et incidents',
         'Préparer une fiche d’essai et contrôler la complétude des observations déposées ; ne jamais déclarer l’essai exécuté.',
         'Seul l’expérimentateur atteste la réalisation et les mesures.'),
    task('r1-notebook', 'R1', 'Tenir le cahier de laboratoire',
         'Essai daté, protocole, paramètres, observations, auteur',
         ['Créer une entrée datée', 'Relier protocole et données', 'Consigner incidents et corrections', 'Faire vérifier la traçabilité'],
         'Entrée de cahier traçable',
         'Structurer les notes fournies, relever les champs manquants et préparer un résumé de l’essai.',
         'L’auteur vérifie l’exactitude et l’intégrité de l’entrée.'),
    task('r1-code', 'R1', 'Écrire ou adapter du code scientifique',
         'Spécification, données d’exemple, environnement et tests attendus',
         ['Définir entrées, sorties et unités', 'Écrire le programme', 'Exécuter des tests dans un environnement approuvé', 'Conserver versions et résultats'],
         'Code, mode d’emploi et résultats des tests',
         'Proposer une implémentation, des tests et une revue statique ; indiquer explicitement ce qui n’a pas été exécuté.',
         'Le chercheur exécute et valide les résultats avant usage.'),
    task('r1-data', 'R1', 'Nettoyer et analyser les données',
         'Jeu de données, dictionnaire de variables, méthode statistique',
         ['Décrire données et exclusions', 'Appliquer un traitement reproductible', 'Vérifier unités et incertitudes', 'Interpréter sans confondre calcul et preuve'],
         'Analyse reproductible, figures et limites',
         'Proposer plan d’analyse, contrôles et code ; commenter uniquement les sorties réellement fournies.',
         'Le doctorant vérifie le traitement et l’interprétation.'),
    task('r1-supervision', 'R1', 'Discuter les résultats avec l’encadrant',
         'Résultat, preuve, blocage et décision demandée',
         ['Préparer une note concise', 'Partager les preuves', 'Recevoir les commentaires', 'Consigner la décision et la suite'],
         'Compte rendu de réunion et décisions',
         'Synthétiser résultats, incertitudes et questions pour la réunion.',
         'Le directeur de thèse valide ou corrige ses propres décisions.'),
    task('r1-writing', 'R1', 'Rédiger thèse et articles',
         'Plan, données validées, sources, consignes de la revue',
         ['Définir l’argument', 'Rédiger section par section', 'Relier affirmations et preuves', 'Faire relire et réviser'],
         'Manuscrit ou article versionné',
         'Préparer plan, brouillon ou relecture critique avec provenance et points à vérifier.',
         'Le doctorant et les coauteurs approuvent la version soumise.'),
    task('r1-reviewers', 'R1', 'Répondre aux relecteurs',
         'Commentaires, version soumise, nouvelles analyses autorisées',
         ['Numéroter les remarques', 'Associer chaque remarque à une action', 'Modifier le manuscrit', 'Rédiger la réponse point par point'],
         'Lettre de réponse et manuscrit révisé',
         'Proposer une matrice commentaire–action–preuve et un brouillon de réponse.',
         'Les auteurs vérifient chaque modification et réponse.'),
    task('r1-conference', 'R1', 'Préparer conférence et poster',
         'Résultats validés, public, format, droits de diffusion',
         ['Choisir le message', 'Préparer résumé et figures', 'Construire poster ou présentation', 'Faire approuver la diffusion'],
         'Résumé, poster ou présentation',
         'Préparer narration, plan des supports et questions probables sans inventer de résultat.',
         'Les auteurs valident chiffres et éléments publiables.'),
    task('r1-committee', 'R1', 'Préparer le comité de suivi',
         'Objectifs, travaux, résultats, difficultés, calendrier',
         ['Rassembler les preuves', 'Décrire progrès et écarts', 'Présenter les risques et la suite', 'Consigner les recommandations'],
         'Rapport annuel et décisions du comité',
         'Proposer un rapport d’avancement et signaler les éléments non documentés.',
         'Le doctorant et le comité vérifient le rapport et ses décisions.'),
    task('r1-teaching', 'R1', 'Préparer l’enseignement',
         'Objectifs pédagogiques, niveau, durée, programme',
         ['Définir compétences visées', 'Préparer supports et exercices', 'Vérifier corrigés et références', 'Adapter après le cours'],
         'Support de cours, exercices et corrigé',
         'Proposer plan, explications, exercices et corrigés à vérifier.',
         'L’enseignant valide exactitude et niveau pédagogique.'),
    task('r1-defense', 'R1', 'Préparer soutenance et après-thèse',
         'Contributions, manuscrit final, jury, préférences de carrière',
         ['Synthétiser contributions et limites', 'Préparer exposé et questions', 'Comparer les voies après la thèse', 'Fixer prochaines démarches'],
         'Présentation de soutenance et plan de transition',
         'Préparer trame orale, questions possibles et comparaison argumentée des options professionnelles.',
         'Le doctorant décide de sa présentation et de sa trajectoire.'),
    task('r1-disclosure', 'R1', 'Décider ce qui peut être divulgué',
         'Résultat, article prévu, financeurs, contrats et droits connus',
         ['Lister les contenus envisagés', 'Identifier publications et engagements', 'Demander avis encadrement/valorisation', 'Consigner l’accord avant diffusion'],
         'Décision de diffusion datée et périmètre autorisé',
         'Préparer une fiche factuelle sur le contenu et les inconnues ; ne pas conclure sur les droits.',
         'Les personnes habilitées autorisent ou refusent la diffusion.'),

    task('r2-manuscript', 'R2', 'Corriger et déposer le manuscrit final',
         'Remarques du jury, manuscrit, règles de dépôt',
         ['Lister les corrections', 'Modifier le manuscrit', 'Contrôler chaque demande', 'Déposer puis conserver la preuve'],
         'Manuscrit final et confirmation de dépôt',
         'Transformer les remarques en liste de vérification et relire la réponse apportée à chacune.',
         'Le docteur valide et effectue le dépôt institutionnel.'),
    task('r2-articles', 'R2', 'Finaliser les derniers articles',
         'Résultats validés, coauteurs, consignes éditoriales',
         ['Clore les analyses', 'Rédiger et relire', 'Obtenir accord des coauteurs', 'Soumettre et suivre la revue'],
         'Article soumis et suivi éditorial',
         'Préparer sections, réponses et points restant à vérifier.',
         'Les coauteurs valident la soumission et les conclusions.'),
    task('r2-handover', 'R2', 'Transmettre données, code et protocoles',
         'Jeux de données, code, protocoles, successeur, accès',
         ['Inventorier les ressources', 'Documenter versions et reproduction', 'Transférer les accès autorisés', 'Faire accuser réception'],
         'Dossier de passation et accusé de réception',
         'Proposer inventaire, mode d’emploi et liste des éléments manquants.',
         'Le docteur et le successeur vérifient ensemble la reprise.'),
    task('r2-jobs', 'R2', 'Chercher un poste et candidater',
         'CV, compétences, offres, exemples de travaux partageables',
         ['Choisir les postes', 'Adapter CV et lettre', 'Vérifier les éléments publiables', 'Envoyer et suivre les candidatures'],
         'Dossier de candidature et suivi',
         'Comparer le profil aux critères d’une offre et proposer CV ou lettre adaptés.',
         'Le candidat vérifie et envoie lui-même sa candidature.'),
    task('r2-startup', 'R2', 'Explorer la création d’une startup',
         'Résultat scientifique, besoin client, droits, équipe, incubateur',
         ['Formuler l’usage potentiel', 'Lister les preuves techniques et commerciales', 'Contacter valorisation et incubateur', 'Préparer le premier dossier'],
         'Dossier d’opportunité et contacts à instruire',
         'Préparer hypothèses de marché, risques, preuves manquantes et questions pour les interlocuteurs.',
         'Le docteur et la valorisation confirment faisabilité et droits.'),
    task('r2-decision', 'R2', 'Choisir entre postdoc, emploi et startup',
         'Préférences, contraintes, échéances, offres et informations manquantes',
         ['Définir critères personnels', 'Comparer les trois options', 'Vérifier hypothèses et dates', 'Décider et fixer les prochaines actions'],
         'Tableau de décision et plan d’action',
         'Structurer les options, compromis, inconnues et échéances sans décider à la place du docteur.',
         'Le docteur choisit sa voie.'),

    task('r3-supervision', 'R3', 'Préparer et suivre l’encadrement',
         'Progrès de chaque doctorant, blocages, réunions et décisions',
         ['Recevoir le point du doctorant', 'Préparer la réunion', 'Arbitrer les prochaines étapes', 'Consigner les décisions'],
         'Compte rendu de supervision',
         'Synthétiser progrès, incertitudes et décisions proposées à partir des éléments partagés.',
         'Le directeur valide ses commentaires et décisions.'),
    task('r3-protocols', 'R3', 'Relire protocoles et résultats',
         'Protocole, données, méthode d’analyse, limites',
         ['Contrôler hypothèses et témoins', 'Examiner données et calculs', 'Demander corrections ou nouvel essai', 'Valider la version révisée'],
         'Avis scientifique et demandes de révision',
         'Préparer une revue critique des contrôles, unités, limites et incohérences visibles.',
         'Le directeur évalue la solidité scientifique.'),
    task('r3-manuscripts', 'R3', 'Relire manuscrits et articles',
         'Manuscrit, sources, figures, données et contributions',
         ['Lire l’argument', 'Comparer affirmations et preuves', 'Annoter les passages', 'Valider la nouvelle version'],
         'Commentaires localisés et décision de relecture',
         'Proposer commentaires et questions sur les passages fournis.',
         'Le directeur vérifie les critiques et approuve sa relecture.'),
    task('r3-publication', 'R3', 'Publier avec les doctorants',
         'Résultats, coauteurs, revue visée, droits de diffusion',
         ['Définir contributions', 'Rédiger et réviser', 'Obtenir accord des coauteurs', 'Soumettre puis répondre aux retours'],
         'Article, accord des coauteurs et suivi éditorial',
         'Préparer plan, brouillon et matrice des commentaires éditoriaux.',
         'Les coauteurs approuvent le contenu et la soumission.'),
    task('r3-funding', 'R3', 'Monter un dossier de financement',
         'Appel, critères, résultats préliminaires, partenaires et budget',
         ['Lire les critères de l’appel', 'Définir objectifs et programme', 'Chiffrer avec les services concernés', 'Faire relire et déposer'],
         'Dossier de financement et preuve de dépôt',
         'Préparer argumentaire, plan de travail, risques et liste des pièces manquantes.',
         'Le porteur et les services habilités valident budget et dépôt.'),
    task('r3-funder-report', 'R3', 'Rendre compte aux financeurs',
         'Convention, jalons, résultats, livrables et dépenses',
         ['Rassembler les preuves', 'Comparer réalisé et prévu', 'Expliquer écarts', 'Faire valider et transmettre'],
         'Rapport d’avancement justifié',
         'Préparer une synthèse jalon par jalon et signaler les preuves absentes.',
         'Le responsable scientifique valide le rapport transmis.'),
    task('r3-jury', 'R3', 'Participer aux comités et jurys',
         'Dossier communiqué, critères et obligations de confidentialité',
         ['Lire le dossier autorisé', 'Préparer questions et avis', 'Participer à la séance', 'Consigner uniquement les éléments autorisés'],
         'Questions et rapport de comité ou jury',
         'Proposer une grille de lecture et des questions critiques à partir du dossier fourni.',
         'Le membre du jury conserve son jugement et la confidentialité.'),
    task('r3-peer-review', 'R3', 'Relire pour une revue scientifique',
         'Manuscrit confidentiel, consignes de la revue, critères',
         ['Vérifier les règles de confidentialité', 'Évaluer méthode et portée', 'Rédiger avis structuré', 'Soumettre dans le système de la revue'],
         'Rapport d’évaluation confidentiel',
         'Aider à structurer la grille et, seulement si la revue l’autorise, critiquer les extraits fournis.',
         'Le relecteur respecte les règles de la revue et signe son avis.'),
    task('r3-teaching', 'R3', 'Donner des cours',
         'Programme, objectifs, niveau, retours des étudiants',
         ['Planifier les séances', 'Préparer supports et évaluations', 'Vérifier corrigés', 'Adapter après retour'],
         'Cours, exercices, évaluations et corrigés',
         'Proposer supports et exercices alignés avec les objectifs pédagogiques.',
         'L’enseignant valide exactitude et équité des évaluations.'),
    task('r3-disclosure', 'R3', 'Arbitrer publication et confidentialité',
         'Résultat, calendrier d’article, partenaires, accords et droits connus',
         ['Identifier les contenus sensibles', 'Consulter valorisation et coauteurs', 'Choisir date et périmètre de diffusion', 'Consigner l’accord et ses motifs'],
         'Décision de divulgation datée',
         'Préparer une note factuelle avec risques et inconnues, sans conclure sur les droits.',
         'Le directeur et les ayants droit habilités prennent la décision.'),
]

BY_ID = {item['id']: item for item in TASKS}

# These tasks cannot be marked finished from the author's checklist alone.
REQUIRES_PEER_REVIEW = {'r1-hypotheses', 'r1-experiment-design', 'r1-supervision', 'r1-disclosure',
                        'r3-disclosure'}
for item in TASKS:
    item['requires_peer_review'] = item['id'] in REQUIRES_PEER_REVIEW


def checkpoint(code, title, guidance, before='done'):
    return {'code': code, 'title': title, 'guidance': guidance, 'before': before}


# A local attestation records who claims an external action, when, and which
# evidence supports it. Passage cannot itself certify these third-party facts.
CHECKPOINTS = {
    'r1-experiment-run': [checkpoint('experiment_performed', 'Essai réalisé et observations conservées',
        'L’expérimentateur atteste la date de l’essai et relie le relevé ou compte rendu.')],
    'r1-code': [checkpoint('tests_executed', 'Tests exécutés dans un environnement approuvé',
        'Relier les sorties de tests et préciser l’environnement utilisé.')],
    'r1-data': [checkpoint('analysis_executed', 'Traitement des données exécuté',
        'Relier le résultat ou script exécuté ; le profil descriptif de Passage ne suffit pas.')],
    'r1-conference': [checkpoint('dissemination_cleared', 'Diffusion approuvée',
        'Relier l’accord de diffusion avant de considérer le support prêt à partager.')],
    'r1-committee': [checkpoint('committee_recommendations', 'Recommandations du comité reçues',
        'Relier le compte rendu ou l’avis communiqué par le comité de suivi.')],
    'r1-disclosure': [checkpoint('agent_clearance', 'Partage avec un agent autorisé',
        'Relier les règles ou l’accord qui permettent de transmettre ces informations au modèle choisi.', 'agent'),
        checkpoint('rights_cleared', 'Périmètre de diffusion autorisé',
        'Relier l’accord des personnes habilitées et préciser le contenu couvert.')],
    'r2-manuscript': [checkpoint('repository_deposit', 'Manuscrit déposé',
        'Relier la confirmation du dépôt institutionnel et sa date.')],
    'r2-articles': [checkpoint('coauthors_approved', 'Accord des coauteurs reçu',
        'Relier l’accord portant sur la version soumise.'),
        checkpoint('article_submitted', 'Article soumis',
        'Relier l’accusé de réception de la revue et sa date.')],
    'r2-handover': [checkpoint('recipient_acknowledged', 'Reprise confirmée par le successeur',
        'Relier un accusé de réception ou un compte rendu de passation.')],
    'r2-jobs': [checkpoint('application_sent', 'Candidature envoyée',
        'Relier un accusé de candidature ou une preuve d’envoi ; une tâche suit une candidature.')],
    'r2-startup': [checkpoint('stakeholder_contacted', 'Valorisation ou incubateur contacté',
        'Relier un échange ou compte rendu ; ce contact ne valide pas les droits.')],
    'r3-publication': [checkpoint('coauthors_approved', 'Accord des coauteurs reçu',
        'Relier l’accord sur la version soumise.'),
        checkpoint('article_submitted', 'Article soumis',
        'Relier la confirmation de soumission.')],
    'r3-funding': [checkpoint('budget_approved', 'Budget validé par les services habilités',
        'Relier l’accord sur la version budgétaire du dossier.'),
        checkpoint('funding_submitted', 'Dossier de financement déposé',
        'Relier la confirmation de dépôt.')],
    'r3-funder-report': [checkpoint('report_transmitted', 'Rapport transmis au financeur',
        'Relier l’accusé de transmission du rapport validé.')],
    'r3-jury': [checkpoint('agent_clearance', 'Usage de l’agent autorisé pour ce dossier',
        'Relier les règles de confidentialité autorisant le modèle et les pièces partagées.', 'agent'),
        checkpoint('session_attended', 'Séance tenue et avis autorisé consigné',
        'Relier le compte rendu ou l’avis que le membre du jury peut conserver.')],
    'r3-peer-review': [checkpoint('agent_clearance', 'Usage de l’IA autorisé par la revue',
        'Relier la politique de la revue ou son accord explicite pour les extraits transmis.', 'agent'),
        checkpoint('review_submitted', 'Avis soumis à la revue',
        'Relier la confirmation de soumission de l’avis signé.')],
    'r3-teaching': [checkpoint('course_delivered', 'Cours donné et retour consigné',
        'Relier la séance ou les retours utilisés pour adapter le support.')],
    'r3-disclosure': [checkpoint('agent_clearance', 'Partage avec un agent autorisé',
        'Relier les règles ou l’accord permettant de transmettre ces informations au modèle choisi.', 'agent'),
        checkpoint('rights_cleared', 'Diffusion autorisée par les ayants droit',
        'Relier la décision et préciser son périmètre et sa date.')],
}
for item in TASKS:
    item['checkpoints'] = CHECKPOINTS.get(item['id'], [])


# Short, task-specific working questions. They guide both the person filling
# the dossier and the agent drafting from it; they are not facts by themselves.
WORKSHEET_QUESTIONS = {
    'r1-literature': ('Question et critères de sélection', 'Sources lues et résultats principaux', 'Qualité, limites et lacunes du corpus'),
    'r1-state-art': ('Thèmes et plan de la synthèse', 'Résultats convergents et contradictoires', 'Place de la contribution de thèse'),
    'r1-hypotheses': ('Question mesurable', 'Hypothèses concurrentes et prédictions', 'Observations qui les départageraient'),
    'r1-experiment-design': ('Hypothèse, variables et témoins', 'Mesures, unités et protocole', 'Risques, critères d’arrêt et approbation'),
    'r1-experiment-run': ('Protocole et autorisations applicables', 'Paramètres, mesures et écarts observés', 'Incidents et emplacement des données brutes'),
    'r1-notebook': ('Date, auteur et essai concerné', 'Observations brutes et liens vers les données', 'Corrections, incidents et vérification'),
    'r1-code': ('Entrées, sorties, unités et environnement', 'Version du programme et mode d’emploi', 'Tests attendus, sorties obtenues et limites'),
    'r1-data': ('Jeu de données, variables et exclusions', 'Traitement, version du code et paramètres', 'Résultats, incertitudes et interprétation'),
    'r1-supervision': ('Résultats et preuves à discuter', 'Questions ou décisions attendues', 'Commentaires reçus et actions décidées'),
    'r1-writing': ('Argument et plan des sections', 'Affirmations et sources ou données associées', 'Relectures et révisions à effectuer'),
    'r1-reviewers': ('Commentaires numérotés des relecteurs', 'Action et modification par commentaire', 'Preuve, réponse et vérification des auteurs'),
    'r1-conference': ('Public et message principal', 'Résultats et figures autorisés', 'Format, questions probables et accord de diffusion'),
    'r1-committee': ('Objectifs et progrès depuis le dernier comité', 'Écarts, difficultés et risques', 'Recommandations reçues et suite décidée'),
    'r1-teaching': ('Objectifs, public et durée', 'Supports, exercices et corrigés', 'Points à vérifier et retours après le cours'),
    'r1-defense': ('Contributions et limites à présenter', 'Plan oral et questions du jury', 'Options après la thèse et prochaines démarches'),
    'r1-disclosure': ('Contenu envisagé pour la diffusion', 'Engagements, titulaires des droits et inconnues', 'Avis reçus et périmètre de la décision'),
    'r2-manuscript': ('Corrections demandées par le jury', 'Modification et contrôle de chaque demande', 'Version finale et référence du dépôt'),
    'r2-articles': ('Résultats et version de l’article', 'Accords des coauteurs et points ouverts', 'Soumission et état éditorial'),
    'r2-handover': ('Inventaire des données, codes et protocoles', 'Versions, accès et mode de reproduction', 'Destinataire, transmission et réception'),
    'r2-jobs': ('Poste, critères et échéance', 'Expériences et documents partageables', 'Version envoyée et état de la candidature'),
    'r2-startup': ('Besoin client et usage proposé', 'Preuves techniques, marché et droits à vérifier', 'Interlocuteurs contactés et questions ouvertes'),
    'r2-decision': ('Critères et contraintes personnels', 'Comparaison postdoc, emploi et startup', 'Décision, échéances et prochaines actions'),
    'r3-supervision': ('Progrès et blocages du doctorant', 'Questions à traiter en réunion', 'Décisions validées et suivi'),
    'r3-protocols': ('Hypothèses, témoins et critères de qualité', 'Données, calculs et incohérences examinés', 'Corrections demandées et version recontrôlée'),
    'r3-manuscripts': ('Argument, figures et passages examinés', 'Affirmations sans preuve ou citations à revoir', 'Commentaires et décision sur la nouvelle version'),
    'r3-publication': ('Contributions et ordre des coauteurs', 'Version, données et droits vérifiés', 'Accords, soumission et retours éditoriaux'),
    'r3-funding': ('Appel, critères et échéance', 'Objectifs, lots de travail et partenaires', 'Budget, accords et pièces de dépôt'),
    'r3-funder-report': ('Jalons et livrables convenus', 'Réalisé, preuves et écarts', 'Validation et transmission du rapport'),
    'r3-jury': ('Dossier et critères autorisés', 'Questions et appréciation personnelle', 'Éléments consignables après la séance'),
    'r3-peer-review': ('Règles de confidentialité et usage de l’IA', 'Méthode, résultats et limites du manuscrit', 'Avis signé et référence de soumission'),
    'r3-teaching': ('Objectifs, niveau et calendrier', 'Supports et évaluations avec corrigés', 'Séances tenues et adaptation après retour'),
    'r3-disclosure': ('Contenus sensibles et calendrier visé', 'Avis des coauteurs, partenaires et valorisation', 'Décision, ayants droit et périmètre autorisé'),
}
assert set(WORKSHEET_QUESTIONS) == set(BY_ID)
for item in TASKS:
    item['worksheet_questions'] = [
        {'code': 'q'+str(index+1), 'title': title}
        for index, title in enumerate(WORKSHEET_QUESTIONS[item['id']])
    ]


# Repeatable evidence rows. A worksheet frames the task; a register follows
# each source, trial, comment, application, budget item or decision separately.
REGISTERS = {
    'r1-literature': ('Fiches de lecture', ('Source et identifiant', 'Résultat et méthode', 'Limites', 'Pertinence pour la question')),
    'r1-state-art': ('Comparaison par thème', ('Thème', 'Résultats convergents', 'Contradictions et sources', 'Place de la thèse')),
    'r1-hypotheses': ('Registre des hypothèses', ('Hypothèse', 'Prédiction mesurable', 'Test discriminant', 'État ou décision')),
    'r1-experiment-design': ('Éléments du protocole', ('Variable ou témoin', 'Réglage ou méthode', 'Mesure et unité', 'Risque ou critère d’arrêt')),
    'r1-experiment-run': ('Essais et observations', ('Essai et date', 'Paramètres', 'Mesures ou observations', 'Écarts et incidents')),
    'r1-notebook': ('Entrées du cahier', ('Date et auteur', 'Protocole et essai', 'Observation et fichier', 'Correction ou incident')),
    'r1-code': ('Composants et tests', ('Composant et version', 'Entrées et sorties', 'Test et résultat', 'Limite ou anomalie')),
    'r1-data': ('Traitements et résultats', ('Jeu, variable ou exclusion', 'Traitement et paramètres', 'Sortie et incertitude', 'Interprétation et limite')),
    'r1-supervision': ('Questions et décisions', ('Résultat ou blocage', 'Preuve apportée', 'Question à l’encadrant', 'Décision et responsable')),
    'r1-writing': ('Sections et arguments', ('Section', 'Affirmation principale', 'Source ou donnée', 'Relecture et modification')),
    'r1-reviewers': ('Réponses aux relecteurs', ('Remarque numérotée', 'Action ou analyse', 'Preuve et passage modifié', 'Réponse proposée')),
    'r1-conference': ('Messages et supports', ('Message ou figure', 'Résultat vérifié', 'Public et format', 'Accord de diffusion')),
    'r1-committee': ('Avancement et recommandations', ('Objectif ou jalon', 'Travail et preuve', 'Écart ou risque', 'Recommandation et suite')),
    'r1-teaching': ('Séances et exercices', ('Séance et objectif', 'Support ou exercice', 'Corrigé ou contrôle', 'Retour et adaptation')),
    'r1-defense': ('Arguments de soutenance', ('Contribution ou question', 'Preuve et limite', 'Diapositive ou réponse', 'Suite envisagée')),
    'r1-disclosure': ('Contenus à arbitrer', ('Contenu ou résultat', 'Engagement et ayant droit', 'Avis ou autorisation', 'Périmètre et décision')),
    'r2-manuscript': ('Corrections du jury', ('Demande du jury', 'Passage ou action', 'Contrôle effectué', 'Version et dépôt')),
    'r2-articles': ('Articles et suivi', ('Article et version', 'Résultat ou section', 'Accord des coauteurs', 'Soumission et état')),
    'r2-handover': ('Inventaire de passation', ('Ressource et version', 'Accès et emplacement', 'Mode de reprise', 'Destinataire et réception')),
    'r2-jobs': ('Candidatures', ('Poste et employeur', 'Critères et échéance', 'Dossier envoyé', 'État et prochaine action')),
    'r2-startup': ('Hypothèses d’opportunité', ('Besoin ou usage', 'Preuve technique', 'Preuve marché ou droit', 'Contact et prochaine vérification')),
    'r2-decision': ('Options de carrière', ('Option', 'Critères favorables', 'Contraintes et inconnues', 'Échéance et action')),
    'r3-supervision': ('Suivi des doctorants', ('Doctorant ou sujet', 'Progrès et preuve', 'Blocage ou arbitrage', 'Décision et échéance')),
    'r3-protocols': ('Points de revue scientifique', ('Protocole ou résultat', 'Contrôle effectué', 'Écart ou faiblesse', 'Correction demandée')),
    'r3-manuscripts': ('Commentaires de manuscrit', ('Passage ou figure', 'Affirmation et preuve', 'Commentaire', 'Décision sur la version')),
    'r3-publication': ('Contributions et retours', ('Article ou coauteur', 'Contribution ou remarque', 'Accord ou correction', 'Version et état')),
    'r3-funding': ('Lots et budget', ('Lot ou poste', 'Objectif et responsable', 'Montant ou hypothèse', 'Validation et pièce')),
    'r3-funder-report': ('Jalons du financeur', ('Jalon contractuel', 'Réalisé et preuve', 'Écart et explication', 'Validation ou action')),
    'r3-jury': ('Questions et avis autorisés', ('Critère ou dossier', 'Observation permise', 'Question ou appréciation', 'Élément consignable')),
    'r3-peer-review': ('Points de relecture', ('Section ou résultat', 'Observation méthodologique', 'Importance ou limite', 'Avis à transmettre')),
    'r3-teaching': ('Séances et évaluations', ('Séance ou évaluation', 'Objectif et support', 'Corrigé ou barème', 'Retour et adaptation')),
    'r3-disclosure': ('Décisions de confidentialité', ('Contenu', 'Partenaire ou ayant droit', 'Avis et contrainte', 'Périmètre et date')),
}
assert set(REGISTERS) == set(BY_ID)
for item in TASKS:
    register_title, columns = REGISTERS[item['id']]
    item['register'] = {'title': register_title,
                        'columns': [{'code': 'c'+str(index+1), 'title': title}
                                    for index, title in enumerate(columns)]}


assert set(RECIPES) == set(BY_ID)
STEP_TOOLS = {'questions', 'register', 'document', 'file', 'diagram',
              'anchor', 'evidence', 'share'}
for item in TASKS:
    recipes = RECIPES[item['id']]
    assert len(recipes) == len(item['steps']) == 4
    assert all(recipe['agent_help'] and recipe['evidence']
               and recipe['tool'] in STEP_TOOLS for recipe in recipes)
    item['playbook'] = [{'index': index, 'human_action': label, **recipe}
                        for index, (label, recipe) in enumerate(zip(item['steps'], recipes))]
